version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - curl -s -qL -o terraform_install.zip https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip terraform_install.zip -d /usr/bin/
      - pip3 install git-remote-codecommit boto3
  pre_build:
    commands:
      - echo "Setting up environment variables..."
      - echo "Fetching env.properties from S3..."
      - aws s3 cp s3://$ARTIFACTS_BUCKET/lambda/env.properties $CODEBUILD_SRC_DIR/env.properties
      - cat $CODEBUILD_SRC_DIR/env.properties
      - source $CODEBUILD_SRC_DIR/env.properties
      - echo "Lambda VersionId is $VERSION_ID"

      - echo "Assuming Terraform Execution Role..."
      - CREDS=$(aws sts assume-role --role-arn $TF_EXEC_ROLE --role-session-name tf-build)
      - export AWS_ACCESS_KEY_ID=$(echo $CREDS | jq -r .Credentials.AccessKeyId)
      - export AWS_SECRET_ACCESS_KEY=$(echo $CREDS | jq -r .Credentials.SecretAccessKey)
      - export AWS_SESSION_TOKEN=$(echo $CREDS | jq -r .Credentials.SessionToken)
      - cd IaC/
      - terraform init -reconfigure -backend-config=${backend_config}
      - terraform validate
  
  build:
    commands:
      - terraform apply -var-file="${env_file}" -var s3_object_version="$VERSION_ID" --auto-approve